In [1]:
import numpy as np

ratings = np.array([4.9, 4.1, 4.8])
votes = np.array([ 775,  787,  918])

In [2]:
ratings.shape

(3,)

In [3]:
ratings.ndim

1

In [4]:
ratings * 3

array([14.7, 12.3, 14.4])

In [8]:
matrix = np.arange(11,20).reshape(3,3)

In [9]:
matrix

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [10]:
matrix * 3

array([[33, 36, 39],
       [42, 45, 48],
       [51, 54, 57]])

In [11]:
ratings * votes

array([3797.5, 3226.7, 4406.4])

In [12]:
matrix1 = np.arange(11,20).reshape(3,3)
matrix2 = np.arange(1,10).reshape(3,3)

In [14]:
matrix1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [13]:
matrix1 * matrix2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [15]:
matrix1 @ matrix2

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [16]:
col_matrix = np.array([[1], [2], [3]])
row_matrix = np.array([[10, 20, 30]])

In [17]:
col_matrix.shape

(3, 1)

In [18]:
row_matrix.shape

(1, 3)

In [19]:
col_matrix.ndim

2

In [20]:
row_matrix.ndim

2

In [21]:
col_matrix + row_matrix

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [22]:
col_matrix + 3

array([[4],
       [5],
       [6]])

In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])

In [25]:
array1.shape,array1.ndim

((3,), 1)

In [26]:
array2.shape,array2.ndim

((2, 2), 2)

In [27]:
array1 + array2 # summation not possible between different dimention matrix

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [28]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

In [29]:
array1 + array2

array([[11, 12, 13],
       [24, 25, 26]])

In [30]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])

array1 + array2

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [31]:
array1.shape,array1.ndim

((2, 3), 2)

In [32]:
array2.shape,array2.ndim

((1, 2), 2)

In [33]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])

In [34]:
array1 + array2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [35]:
array1_copy_pasted= np.tile(array1,(3,1))

array1_copy_pasted

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [36]:
array1_copy_pasted.shape

(3, 3)

In [37]:
array1_copy_pasted + array2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [38]:
array2_copy_pasted= np.tile(array2,(1,3))

array2_copy_pasted

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [39]:
array1_copy_pasted + array2_copy_pasted

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [40]:
def categorize_rating(rating):
    "Categorize ratings into high or low."""
    if rating >= 4.5:
        return "High"
    else:
        return "Low"

In [41]:
ratings

array([4.9, 4.1, 4.8])

In [42]:
categorize_rating(ratings)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [43]:
categorize_rating_np = np.vectorize(categorize_rating)

In [44]:
categorize_rating_np(ratings)

array(['High', 'Low', 'High'], dtype='<U4')

In [45]:
array_1d= np.arange(1,10)

In [46]:
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.split(array_1d,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [48]:
np.split(array_1d,2)

ValueError: array split does not result in an equal division

In [49]:
# 2D

array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

In [50]:
array_2d.shape

(2, 4)

In [51]:
np.split(array_2d, 2, axis = 1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [52]:
np.split(array_2d, 2, axis = 0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [53]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [54]:
v_stack_result= np.vstack([array1,array2])

In [55]:
v_stack_result

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
h_stack_result= np.hstack([array1,array2])

In [57]:
h_stack_result

array([1, 2, 3, 4, 5, 6])

In [58]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5])

In [59]:
h_stack_result= np.hstack([array1,array2])

In [60]:
v_stack_result= np.vstack([array1,array2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [62]:
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

In [63]:
np.concatenate([array4,array5],axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [64]:
np.concatenate([array4,array5],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])