In [ ]:
import numpy as np

ratings = np.array([4.9, 4.1, 4.8])
votes = np.array([ 775,  787,  918])

In [ ]:
ratings.shape

(3,)

In [ ]:
ratings.ndim

1

In [ ]:
ratings * 3

array([14.7, 12.3, 14.4])

In [ ]:
matrixx= np.arange(11,20).reshape(3,3)

In [ ]:
matrixx

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
matrixx * 3

array([[33, 36, 39],
       [42, 45, 48],
       [51, 54, 57]])

In [ ]:
ratings * votes

array([3797.5, 3226.7, 4406.4])

In [ ]:
matrix1= np.arange(11,20).reshape(3,3)
matrix2= np.arange(1,10).reshape(3,3)

In [ ]:
matrix1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix1 * matrix2 #element wise multiplication

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [ ]:
matrix1 @ matrix2

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [ ]:
col_matrix = np.array([[1], [2], [3]])
row_matrix = np.array([[10, 20, 30]])

In [ ]:
col_matrix.ndim

2

In [ ]:
row_matrix.ndim

2

In [ ]:
col_matrix + row_matrix

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [ ]:
col_matrix + 3

array([[4],
       [5],
       [6]])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])

In [ ]:
array1.shape, array1.ndim

((3,), 1)

In [ ]:
array2.shape, array2.ndim

((2, 2), 2)

In [ ]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

In [ ]:
array1 + array2

array([[11, 12, 13],
       [24, 25, 26]])

In [ ]:
#test
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])

array1 + array2

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [ ]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])

In [ ]:
array1 + array2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
array1_copy_pasted= np.tile(array1,(3,1))

In [ ]:
array1

array([[1, 2, 3]])

In [ ]:
array1_copy_pasted

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
array1_copy_pasted + array2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
array2_copy_pasted= np.tile(array2,(1,3))

In [ ]:
array1_copy_pasted

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
array2_copy_pasted

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
array1_copy_pasted + array2_copy_pasted

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
def categorize_rating(rating):
    "Categorize ratings into high or low."""
    if rating >= 4.5:
        return "High"
    else:
        return "Low"


In [ ]:
ratings

array([4.9, 4.1, 4.8])

In [ ]:
categorize_rating(ratings)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
categorize_rating_np = np.vectorize(categorize_rating)

In [ ]:
categorize_rating_np(ratings)

array(['High', 'Low', 'High'], dtype='<U4')

In [ ]:
array_1d= np.arange(1,10)

In [ ]:
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(array_1d,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
np.split(array_1d,2)

ValueError: array split does not result in an equal division

In [ ]:
# 2D

array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])


In [ ]:
array_2d.shape

(2, 4)

In [ ]:
np.split(array_2d, 2, axis = 1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [ ]:
np.split(array_2d, 2, axis = 0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [ ]:
v_stack_result= np.vstack([array1,array2])

In [ ]:
v_stack_result

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
h_stack_result= np.hstack([array1,array2])

In [ ]:
h_stack_result

array([1, 2, 3, 4, 5, 6])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5])

In [ ]:
v_stack_result= np.vstack([array1,array2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
#2 mins to give me a basic array that can fail my hstack

array1 = np.array([1, 2, 3])
array2= np.array([[4],[5], [6]])

In [ ]:
h_stack_result= np.hstack([array1,array2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

In [ ]:
np.concatenate([array4, array5], axis=0) #concatenate along rows

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.concatenate((a, b), axis=1)) #concatenate along columns

[[1 2 3 4]]


In [ ]:
np.concatenate([array4, array5], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])