In [1]:
import numpy as np

x= [1, "Suraaj", True, 10.33 ]

y = np.array([1, "Suraaj", True, 10.33 ])

y

array(['1', 'Suraaj', 'True', '10.33'], dtype='<U32')

In [2]:
z= np.array([1, True, 10.33 ])
z

array([ 1.  ,  1.  , 10.33])

In [3]:
s= np.array([1, True ])
s

array([1, 1])

In [4]:
[10,20,30,40,2,3,4,5,6] * 2

[10, 20, 30, 40, 2, 3, 4, 5, 6, 10, 20, 30, 40, 2, 3, 4, 5, 6]

In [5]:
c = [10,20,30,40,2,3,4,5,6]
d = []
for i in c:
  d.append(i*2)
d

[20, 40, 60, 80, 4, 6, 8, 10, 12]

In [6]:
np.array([10,20,30,40,2,3,4,5,6]) * 2

array([20, 40, 60, 80,  4,  6,  8, 10, 12])

In [7]:
np.array([10,20,30,40,2,3,4,5,6]) + np.array([10,20,30,40,2,3,4,5,6])

array([20, 40, 60, 80,  4,  6,  8, 10, 12])

In [9]:
f = [10,20,30,40,2,3,4,5,6] + [10,20,30,40,2,3,4,5,6]

In [10]:
g = np.array(f)
g

array([10, 20, 30, 40,  2,  3,  4,  5,  6, 10, 20, 30, 40,  2,  3,  4,  5,
        6])

In [11]:
g.shape

(18,)

In [14]:
print(g.ndim)

print(g.size)

1
18


In [19]:
h = g.astype(str)
g.dtype

dtype('int64')

In [20]:
h.dtype

dtype('<U21')

In [21]:
votes=[778,550,650,780,800,900,1000]
cost=[2000,1500,1000,600,2000,400,500]

details = np.array(votes,cost)

details

TypeError: Field elements must be 2- or 3-tuples, got '2000'