In [ ]:
import numpy as np

In [ ]:
x= np.array([1,2,3,4,5])

In [ ]:
print(x[0])

1


In [ ]:
y= np.arange(1,101)

y

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
y= np.arange(1,100,2)

y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.arange(1,3,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [ ]:
arr[1:10:-2]

array([], dtype=int64)

In [ ]:
arr[10:0:-2]

array([9, 7, 5, 3, 1])

In [ ]:
arr[::-2]

array([9, 7, 5, 3, 1])

In [ ]:
#filterig

votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
#I want to find only restaurants who have got more than 500 votes

votes>=500

array([ True,  True,  True, False, False, False,  True, False,  True,
       False])

In [ ]:
votes[2]

In [ ]:
votes[votes>=500]

array([ 775,  787,  918, 2556,  504])

In [ ]:
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
restaurant= np.array(["R1","R2","R3","R4","R5","R6","R7","R8","R9","R10"])

In [ ]:
restaurant[votes>=500]

array(['R1', 'R2', 'R3', 'R7', 'R9'], dtype='<U3')

In [ ]:
#2D
# Take a sample of 50 restaurants
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

In [ ]:
np.array([sample_votes,sample_costs])

array([[ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
         402.,  150.,  164.,  424.,  918.,   90.,  133.,  144.,   93.,
          62.,  180.,   62.,  148.,  219.,  506.,  172.,  415.,  230.,
        1647., 4884.,  133.,  286.,  540., 2556.,   36.,  244.,  804.,
         679.,  245.,  345.,  618., 1047.,  627.,  354.,  244.,  163.,
         808., 1720.,  868.,  520.,  299.],
       [ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
         500.,  600.,  500.,  450.,  800.,  650.,  800.,  700.,  300.,
         400.,  500.,  600.,  550.,  600.,  500.,  750.,  500.,  650.,
         600.,  750.,  200.,  500.,  800.,  600.,  400.,  300.,  450.,
         850.,  300.,  400.,  750.,  450.,  450.,  800.,  800.,  800.,
         850.,  400., 1200.,  300.,  300.]])

In [ ]:
two_d_array= np.column_stack([sample_votes,sample_costs])

In [ ]:
two_d_array

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 133.,  200.],
       [ 286.,  500.],
       [ 540.,  800.],
       [2556.,  600.],
       [  36.,  400.],
       [ 244.,  300.],
       [ 804.,  450.],
       [ 679.,  850.],
       [ 245.,  300.],
       [ 345.,  400.],
       [ 618.,  750.],
       [1047.,  450.],
       [ 627.,  450.],
       [ 354.,  800.],
       [ 24

In [ ]:
two_d_array.ndim

2

In [ ]:
two_d_array.shape

(50, 2)

In [ ]:
two_d_array.reshape(25,4)

array([[ 775.,  800.,  787.,  800.],
       [ 918.,  800.,   88.,  300.],
       [ 166.,  600.,  286.,  600.],
       [2556.,  600.,  324.,  700.],
       [ 504.,  550.,  402.,  500.],
       [ 150.,  600.,  164.,  500.],
       [ 424.,  450.,  918.,  800.],
       [  90.,  650.,  133.,  800.],
       [ 144.,  700.,   93.,  300.],
       [  62.,  400.,  180.,  500.],
       [  62.,  600.,  148.,  550.],
       [ 219.,  600.,  506.,  500.],
       [ 172.,  750.,  415.,  500.],
       [ 230.,  650., 1647.,  600.],
       [4884.,  750.,  133.,  200.],
       [ 286.,  500.,  540.,  800.],
       [2556.,  600.,   36.,  400.],
       [ 244.,  300.,  804.,  450.],
       [ 679.,  850.,  245.,  300.],
       [ 345.,  400.,  618.,  750.],
       [1047.,  450.,  627.,  450.],
       [ 354.,  800.,  244.,  800.],
       [ 163.,  800.,  808.,  850.],
       [1720.,  400.,  868., 1200.],
       [ 520.,  300.,  299.,  300.]])

In [ ]:
two_d_array.reshape(10,-1) #any dimension you dont know

array([[ 775.,  800.,  787.,  800.,  918.,  800.,   88.,  300.,  166.,
         600.],
       [ 286.,  600., 2556.,  600.,  324.,  700.,  504.,  550.,  402.,
         500.],
       [ 150.,  600.,  164.,  500.,  424.,  450.,  918.,  800.,   90.,
         650.],
       [ 133.,  800.,  144.,  700.,   93.,  300.,   62.,  400.,  180.,
         500.],
       [  62.,  600.,  148.,  550.,  219.,  600.,  506.,  500.,  172.,
         750.],
       [ 415.,  500.,  230.,  650., 1647.,  600., 4884.,  750.,  133.,
         200.],
       [ 286.,  500.,  540.,  800., 2556.,  600.,   36.,  400.,  244.,
         300.],
       [ 804.,  450.,  679.,  850.,  245.,  300.,  345.,  400.,  618.,
         750.],
       [1047.,  450.,  627.,  450.,  354.,  800.,  244.,  800.,  163.,
         800.],
       [ 808.,  850., 1720.,  400.,  868., 1200.,  520.,  300.,  299.,
         300.]])

In [ ]:
two_d_array.reshape(25,-1)

array([[ 775.,  800.,  787.,  800.],
       [ 918.,  800.,   88.,  300.],
       [ 166.,  600.,  286.,  600.],
       [2556.,  600.,  324.,  700.],
       [ 504.,  550.,  402.,  500.],
       [ 150.,  600.,  164.,  500.],
       [ 424.,  450.,  918.,  800.],
       [  90.,  650.,  133.,  800.],
       [ 144.,  700.,   93.,  300.],
       [  62.,  400.,  180.,  500.],
       [  62.,  600.,  148.,  550.],
       [ 219.,  600.,  506.,  500.],
       [ 172.,  750.,  415.,  500.],
       [ 230.,  650., 1647.,  600.],
       [4884.,  750.,  133.,  200.],
       [ 286.,  500.,  540.,  800.],
       [2556.,  600.,   36.,  400.],
       [ 244.,  300.,  804.,  450.],
       [ 679.,  850.,  245.,  300.],
       [ 345.,  400.,  618.,  750.],
       [1047.,  450.,  627.,  450.],
       [ 354.,  800.,  244.,  800.],
       [ 163.,  800.,  808.,  850.],
       [1720.,  400.,  868., 1200.],
       [ 520.,  300.,  299.,  300.]])

In [ ]:
sample_votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402,  150,
        164,  424,  918,   90,  133,  144,   93,   62,  180,   62,  148,
        219,  506,  172,  415,  230, 1647, 4884,  133,  286,  540, 2556,
         36,  244,  804,  679,  245,  345,  618, 1047,  627,  354,  244,
        163,  808, 1720,  868,  520,  299])

In [ ]:
#sum of votes
print(np.sum(sample_votes))

30583


In [ ]:
print(np.mean(sample_votes)) #average
print(np.max(sample_votes)) #maximum value
#minimum value


611.66
4884


In [ ]:
np.sum(two_d_array,axis=0) # 0 --> row, 1 --> column
#axis -->0 all rows will be summed

array([30583., 29350.])

In [ ]:
np.sum(two_d_array,axis=1) #colums are summed

array([1575., 1587., 1718.,  388.,  766.,  886., 3156., 1024., 1054.,
        902.,  750.,  664.,  874., 1718.,  740.,  933.,  844.,  393.,
        462.,  680.,  662.,  698.,  819., 1006.,  922.,  915.,  880.,
       2247., 5634.,  333.,  786., 1340., 3156.,  436.,  544., 1254.,
       1529.,  545.,  745., 1368., 1497., 1077., 1154., 1044.,  963.,
       1658., 2120., 2068.,  820.,  599.])

In [ ]:
print(np.sort(sample_votes))

[  36   62   62   88   90   93  133  133  144  148  150  163  164  166
  172  180  219  230  244  244  245  286  286  299  324  345  354  402
  415  424  504  506  520  540  618  627  679  775  787  804  808  868
  918  918 1047 1647 1720 2556 2556 4884]


In [ ]:
np.sort(sample_votes)[::-1] #descending order

array([4884, 2556, 2556, 1720, 1647, 1047,  918,  918,  868,  808,  804,
        787,  775,  679,  627,  618,  540,  520,  506,  504,  424,  415,
        402,  354,  345,  324,  299,  286,  286,  245,  244,  244,  230,
        219,  180,  172,  166,  164,  163,  150,  148,  144,  133,  133,
         93,   90,   88,   62,   62,   36])

In [ ]:
#if you have to sort the indices
sample_votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402,  150,
        164,  424,  918,   90,  133,  144,   93,   62,  180,   62,  148,
        219,  506,  172,  415,  230, 1647, 4884,  133,  286,  540, 2556,
         36,  244,  804,  679,  245,  345,  618, 1047,  627,  354,  244,
        163,  808, 1720,  868,  520,  299])

In [ ]:
np.argsort(sample_votes)

array([33, 20, 18,  3, 14, 17, 15, 29, 16, 21, 10, 44, 11,  4, 24, 19, 22,
       26, 34, 43, 37, 30,  5, 49,  7, 38, 42,  9, 25, 12,  8, 23, 48, 31,
       39, 41, 36,  0,  1, 35, 45, 47,  2, 13, 40, 27, 46,  6, 32, 28])

In [ ]:
np.sort(two_d_array, axis=0)

array([[  36.,  200.],
       [  62.,  300.],
       [  62.,  300.],
       [  88.,  300.],
       [  90.,  300.],
       [  93.,  300.],
       [ 133.,  300.],
       [ 133.,  400.],
       [ 144.,  400.],
       [ 148.,  400.],
       [ 150.,  400.],
       [ 163.,  450.],
       [ 164.,  450.],
       [ 166.,  450.],
       [ 172.,  450.],
       [ 180.,  500.],
       [ 219.,  500.],
       [ 230.,  500.],
       [ 244.,  500.],
       [ 244.,  500.],
       [ 245.,  500.],
       [ 286.,  550.],
       [ 286.,  550.],
       [ 299.,  600.],
       [ 324.,  600.],
       [ 345.,  600.],
       [ 354.,  600.],
       [ 402.,  600.],
       [ 415.,  600.],
       [ 424.,  600.],
       [ 504.,  600.],
       [ 506.,  650.],
       [ 520.,  650.],
       [ 540.,  700.],
       [ 618.,  700.],
       [ 627.,  750.],
       [ 679.,  750.],
       [ 775.,  750.],
       [ 787.,  800.],
       [ 804.,  800.],
       [ 808.,  800.],
       [ 868.,  800.],
       [ 918.,  800.],
       [ 91

In [ ]:
# matric is a 2d array

x= np.arange(1,10).reshape (3,3)

In [ ]:
x.ndim

2

In [ ]:
x.shape

(3, 3)

In [ ]:
y= np.arange(11,20).reshape (3,-1)

In [ ]:
y.shape

(3, 3)

In [ ]:
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
np.matmul(x,y)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [ ]:
np.dot(x,y)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [ ]:
x @ y

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [ ]:
x= np.arange(1,21).reshape (4,-1)

In [ ]:
x.shape

(4, 5)

In [ ]:
y= np.arange(10,25).reshape (3,-1)

In [ ]:
y.shape

(3, 5)

In [ ]:
np.matmul(x,y.T)

array([[ 190,  265,  340],
       [ 490,  690,  890],
       [ 790, 1115, 1440],
       [1090, 1540, 1990]])

In [ ]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [ ]:
A = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])

A[::-1].T

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [ ]:
arr1 = np.array([1,2,3,6,3,2])
arr2 = np.array([4,2,1,3,3,2])
arr3 = np.zeros(len(arr1))

In [ ]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [ ]:
distinction = np.array([20, 35, 68, 82, 83, 70, 90])

distinction[(60 <= distinction) & (distinction < 80)]

array([68, 70])

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

import numpy as np

birds_arr = np.array(birds)
age_arr = np.array(age)

In [ ]:
birds_arr

array(['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'plovers', 'plovers', 'Cranes', 'spoonbills'], dtype='<U10')

In [ ]:
sort_indices = np.argsort(age_arr)

In [ ]:
sort_indices

array([3, 7, 4, 2, 6, 5, 0, 8, 1, 9])

In [ ]:
result = birds_arr[sort_indices].tolist()

In [ ]:
result

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'spoonbills',
 'Cranes',
 'plovers',
 'spoonbills']

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0

In [ ]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = np.array([[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [ ]:
arr[1, :, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [ ]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


In [ ]:
arr = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])

arr[::,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [ ]:
birds = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
age = np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])

In [ ]:
sort_index = np.argsort(age)

In [ ]:
np.max(sort_index)

np.int64(9)

In [ ]:
birds[np.max(sort_index)]

np.str_('peacock')

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = A.T
print(B[1, 2])

8


In [ ]:
B

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])